name: format

on: push

  black-python:
    name: format python files
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.4.0
      
      - name: run black
        uses: psf/black@stable
